import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/BasicNav/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang='en'>
      <body className={cn(
          "min-h-screen w-full relative flex-col gap-2 font-sans antialiased",
          fontSans.variable
        )}>
          <Toaster />
          <Navbar/>
        {children}
        
      </body>
    </html>
  </ClerkProvider>
  );
}
